name: "update status"
on:
   workflow_dispatch:
   schedule:
     - cron: "0 */3 * * *"

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: false

jobs:
 inits:
    runs-on: ubuntu-latest
    if: ${{ github.triggering_actor == github.repository_owner || github.triggering_actor == 'github-actions' }}
    steps:
      - name: "checkout"
        uses: actions/checkout@v3
        
      - name: "check latest"
        id: check_latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          LATEST_COMMIT="$(curl -s -H "Authorization: Bearer ${GITHUB_TOKEN}" "https://api.github.com/repos/${{ github.repository }}/commits/${{ github.ref }}" | jq -r .sha)"
          if [ "${LATEST_COMMIT}" != "${GITHUB_SHA}" ]; then
            echo "Current commit is not the latest" >&2
            curl -H "Authorization: Bearer ${GITHUB_TOKEN}" -H "Accept: application/vnd.github.v3+json" -X POST -d '{"ref":"'"${{ github.ref }}"'","inputs":{}}' "https://api.github.com/repos/${{ github.repository }}/actions/workflows/auto.yaml/dispatches"
            skip_jobs="true"
          fi
     
      - name: execute
        if: steps.check_latest.outputs.skip_jobs != 'true'
        continue-on-error: true
        env:
          tok_fb: ${{ secrets.TOK_FB }}
          ggl_tok: ${{ secrets.GGL_TOK }}
          file: ${{ secrets.FILE }}
        run: |
          export file="${file}"
          bash main.sh "${tok_fb}" "${ggl_tok}"
        
      - name: update
        if: steps.check_latest.outputs.skip_jobs != 'true'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "updated"
          repository: .
          file_pattern: ./*

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
